// Mock data based on shared/schemas.py from the implementation plan

export const MOCK_HOLDINGS = [
  {
    fundName: 'HDFC Mid-Cap Opportunities Fund',
    isin: 'INF179K01BB2',
    category: 'mid_cap',
    currentValue: 450000,
    investedAmount: 300000,
    unitsHeld: 1154,
    expenseRatio: 0.018,
    directExpenseRatio: 0.0045,
    planType: 'regular',
    topHoldings: [
      { stockName: 'Reliance Industries', weight: 0.07 },
      { stockName: 'HDFC Bank', weight: 0.06 },
      { stockName: 'Infosys', weight: 0.05 },
      { stockName: 'ICICI Bank', weight: 0.04 },
      { stockName: 'TCS', weight: 0.04 },
    ],
  },
  {
    fundName: 'SBI Bluechip Fund',
    isin: 'INF200K01450',
    category: 'large_cap',
    currentValue: 320000,
    investedAmount: 250000,
    unitsHeld: 640,
    expenseRatio: 0.017,
    directExpenseRatio: 0.004,
    planType: 'regular',
    topHoldings: [
      { stockName: 'Reliance Industries', weight: 0.08 },
      { stockName: 'Infosys', weight: 0.07 },
      { stockName: 'HDFC Bank', weight: 0.06 },
      { stockName: 'TCS', weight: 0.05 },
      { stockName: 'Bharti Airtel', weight: 0.04 },
    ],
  },
  {
    fundName: 'ICICI Prudential Multicap Fund',
    isin: 'INF109K01CH0',
    category: 'flexi_cap',
    currentValue: 280000,
    investedAmount: 200000,
    unitsHeld: 890,
    expenseRatio: 0.019,
    directExpenseRatio: 0.005,
    planType: 'regular',
    topHoldings: [
      { stockName: 'Reliance Industries', weight: 0.05 },
      { stockName: 'Infosys', weight: 0.06 },
      { stockName: 'HDFC Bank', weight: 0.05 },
      { stockName: 'L&T', weight: 0.04 },
      { stockName: 'Axis Bank', weight: 0.04 },
    ],
  },
  {
    fundName: 'Mirae Asset Large Cap Fund',
    isin: 'INF769K01EJ8',
    category: 'large_cap',
    currentValue: 180000,
    investedAmount: 150000,
    unitsHeld: 450,
    expenseRatio: 0.014,
    directExpenseRatio: 0.003,
    planType: 'direct',
    topHoldings: [
      { stockName: 'Infosys', weight: 0.08 },
      { stockName: 'HDFC Bank', weight: 0.07 },
      { stockName: 'Reliance Industries', weight: 0.06 },
      { stockName: 'TCS', weight: 0.05 },
      { stockName: 'Kotak Bank', weight: 0.04 },
    ],
  },
  {
    fundName: 'Axis ELSS Tax Saver Fund',
    isin: 'INF846K01EW2',
    category: 'elss',
    currentValue: 150000,
    investedAmount: 120000,
    unitsHeld: 320,
    expenseRatio: 0.016,
    directExpenseRatio: 0.004,
    planType: 'regular',
    topHoldings: [
      { stockName: 'HDFC Bank', weight: 0.08 },
      { stockName: 'Infosys', weight: 0.06 },
      { stockName: 'Bajaj Finance', weight: 0.05 },
      { stockName: 'TCS', weight: 0.05 },
      { stockName: 'Asian Paints', weight: 0.04 },
    ],
  },
  {
    fundName: 'Parag Parikh Flexi Cap Fund',
    isin: 'INF879O01027',
    category: 'flexi_cap',
    currentValue: 220000,
    investedAmount: 180000,
    unitsHeld: 520,
    expenseRatio: 0.015,
    directExpenseRatio: 0.0035,
    planType: 'direct',
    topHoldings: [
      { stockName: 'Alphabet Inc', weight: 0.06 },
      { stockName: 'Microsoft', weight: 0.05 },
      { stockName: 'HDFC Bank', weight: 0.04 },
      { stockName: 'ITC', weight: 0.04 },
      { stockName: 'Bajaj Holdings', weight: 0.03 },
    ],
  },
];

export const MOCK_PORTFOLIO_ANALYTICS = {
  holdings: MOCK_HOLDINGS,
  overallXirr: 0.142,
  fundWiseXirr: {
    'HDFC Mid-Cap Opportunities Fund': 0.162,
    'SBI Bluechip Fund': 0.118,
    'ICICI Prudential Multicap Fund': 0.145,
    'Mirae Asset Large Cap Fund': 0.132,
    'Axis ELSS Tax Saver Fund': 0.125,
    'Parag Parikh Flexi Cap Fund': 0.155,
  },
  overlapMatrix: {
    'Reliance Industries': {
      'HDFC Mid-Cap Opportunities Fund': 0.07,
      'SBI Bluechip Fund': 0.08,
      'ICICI Prudential Multicap Fund': 0.05,
      'Mirae Asset Large Cap Fund': 0.06,
    },
    'HDFC Bank': {
      'HDFC Mid-Cap Opportunities Fund': 0.06,
      'SBI Bluechip Fund': 0.06,
      'ICICI Prudential Multicap Fund': 0.05,
      'Mirae Asset Large Cap Fund': 0.07,
      'Axis ELSS Tax Saver Fund': 0.08,
      'Parag Parikh Flexi Cap Fund': 0.04,
    },
    'Infosys': {
      'HDFC Mid-Cap Opportunities Fund': 0.05,
      'SBI Bluechip Fund': 0.07,
      'ICICI Prudential Multicap Fund': 0.06,
      'Mirae Asset Large Cap Fund': 0.08,
      'Axis ELSS Tax Saver Fund': 0.06,
    },
    'TCS': {
      'HDFC Mid-Cap Opportunities Fund': 0.04,
      'SBI Bluechip Fund': 0.05,
      'Mirae Asset Large Cap Fund': 0.05,
      'Axis ELSS Tax Saver Fund': 0.05,
    },
  },
  expenseRatioDragInr: 12600,
  totalCurrentValue: 1600000,
  totalInvested: 1200000,
};

export const MOCK_USER_PROFILE = {
  age: 32,
  annualIncome: 1800000,
  monthlyExpenses: 60000,
  existingInvestments: 1600000,
  targetRetirementAge: 50,
  targetMonthlyCorpus: 100000,
  riskProfile: 'moderate',
  taxBracket: 0.3,
  hra: 360000,
  section80c: 150000,
  npsContribution: 50000,
  homeLoanInterest: 200000,
};

export const MOCK_REBALANCING_ACTIONS = [
  {
    fundName: 'HDFC Mid-Cap Opportunities Fund',
    action: 'switch',
    percentage: 50,
    targetFund: 'HDFC Mid-Cap Opportunities Fund - Direct Growth',
    taxImpact: 'LTCG of ~₹25,000 applicable',
    rationale: 'Switch from Regular to Direct plan to save ₹6,750 annually in expense ratio',
  },
  {
    fundName: 'SBI Bluechip Fund',
    action: 'hold',
    percentage: 100,
    targetFund: null,
    taxImpact: 'No tax impact',
    rationale: 'Core large-cap holding performing as expected. Good diversification.',
  },
  {
    fundName: 'ICICI Prudential Multicap Fund',
    action: 'reduce',
    percentage: 30,
    targetFund: null,
    taxImpact: 'STCG of ~₹8,000 may apply if held < 1 year',
    rationale: 'High overlap with other funds (Reliance 5%, HDFC Bank 5%). Reduce exposure.',
  },
  {
    fundName: 'Axis ELSS Tax Saver Fund',
    action: 'hold',
    percentage: 100,
    targetFund: null,
    taxImpact: 'Lock-in period applicable',
    rationale: 'ELSS fund with 3-year lock-in. Continue for tax benefits under 80C.',
  },
];

export const MOCK_FIRE_MILESTONES = [
  { month: 1, year: 2026, equitySip: 50000, debtSip: 15000, goldSip: 5000, totalCorpus: 1670000, equityPct: 70, debtPct: 25, notes: 'Start aggressive accumulation phase' },
  { month: 12, year: 2026, equitySip: 52000, debtSip: 16000, goldSip: 5000, totalCorpus: 2450000, equityPct: 70, debtPct: 25, notes: 'Year 1 complete - on track' },
  { month: 24, year: 2027, equitySip: 54000, debtSip: 17000, goldSip: 5500, totalCorpus: 3380000, equityPct: 68, debtPct: 27, notes: 'Begin gradual de-risking' },
  { month: 36, year: 2028, equitySip: 56000, debtSip: 18000, goldSip: 6000, totalCorpus: 4480000, equityPct: 65, debtPct: 30, notes: 'Mid-point review' },
  { month: 60, year: 2030, equitySip: 60000, debtSip: 22000, goldSip: 7000, totalCorpus: 7200000, equityPct: 60, debtPct: 35, notes: 'Nearing corpus target' },
  { month: 84, year: 2032, equitySip: 65000, debtSip: 28000, goldSip: 8000, totalCorpus: 10500000, equityPct: 55, debtPct: 40, notes: 'Accumulation complete' },
  { month: 108, year: 2034, equitySip: 40000, debtSip: 35000, goldSip: 8000, totalCorpus: 14200000, equityPct: 50, debtPct: 45, notes: 'Transition phase' },
  { month: 132, year: 2036, equitySip: 30000, debtSip: 40000, goldSip: 8000, totalCorpus: 18000000, equityPct: 45, debtPct: 50, notes: 'Final glidepath' },
  { month: 156, year: 2038, equitySip: 20000, debtSip: 45000, goldSip: 8000, totalCorpus: 22000000, equityPct: 40, debtPct: 55, notes: 'Retirement ready' },
  { month: 180, year: 2040, equitySip: 0, debtSip: 0, goldSip: 0, totalCorpus: 24000000, equityPct: 35, debtPct: 60, notes: 'FIRE achieved!' },
];

export const MOCK_TAX_COMPARISON = {
  oldRegimeSteps: [
    { description: 'Gross Salary', amount: 1800000 },
    { description: 'Less: Standard Deduction', amount: -50000 },
    { description: 'Less: HRA Exemption', amount: -288000 },
    { description: 'Net Salary Income', amount: 1462000 },
    { description: 'Less: Section 80C (ELSS + EPF)', amount: -150000 },
    { description: 'Less: NPS Contribution (80CCD)', amount: -50000 },
    { description: 'Less: Home Loan Interest (24b)', amount: -200000 },
    { description: 'Taxable Income', amount: 1062000 },
    { description: 'Tax on ₹2.5L @ 0%', amount: 0 },
    { description: 'Tax on ₹2.5L @ 5%', amount: 12500 },
    { description: 'Tax on ₹5L @ 20%', amount: 100000 },
    { description: 'Tax on ₹0.62L @ 30%', amount: 18600 },
    { description: 'Total Tax', amount: 131100 },
    { description: 'Add: Cess @ 4%', amount: 5244 },
    { description: 'Final Tax Liability', amount: 136344 },
  ],
  newRegimeSteps: [
    { description: 'Gross Salary', amount: 1800000 },
    { description: 'Less: Standard Deduction', amount: -75000 },
    { description: 'Taxable Income', amount: 1725000 },
    { description: 'Tax on ₹3L @ 0%', amount: 0 },
    { description: 'Tax on ₹4L @ 5%', amount: 20000 },
    { description: 'Tax on ₹3L @ 10%', amount: 30000 },
    { description: 'Tax on ₹3L @ 15%', amount: 45000 },
    { description: 'Tax on ₹3L @ 20%', amount: 60000 },
    { description: 'Tax on ₹1.25L @ 30%', amount: 37500 },
    { description: 'Total Tax', amount: 192500 },
    { description: 'Add: Cess @ 4%', amount: 7700 },
    { description: 'Final Tax Liability', amount: 200200 },
  ],
  oldTotalTax: 136344,
  newTotalTax: 200200,
  recommendedRegime: 'old',
  savingsAmount: 63856,
  missedDeductions: [
    { item: 'Health Insurance Premium (80D)', potentialSaving: 25000 },
    { item: 'Education Loan Interest (80E)', potentialSaving: 0 },
  ],
  additionalInstruments: [
    {
      instrument: 'NPS Additional Contribution',
      section: '80CCD(1B)',
      maxBenefit: 50000,
      taxSaved: 15600,
      recommendation: 'Consider additional ₹50,000 NPS for extra ₹15,600 tax saving',
    },
    {
      instrument: 'Health Insurance',
      section: '80D',
      maxBenefit: 25000,
      taxSaved: 7800,
      recommendation: 'Get comprehensive health cover - saves tax and provides protection',
    },
  ],
};

export const MOCK_HEALTH_SCORE = [
  {
    dimension: 'Diversification',
    score: 72,
    rationale: 'Good fund variety but high stock overlap (Reliance in 4 funds, HDFC Bank in 6 funds)',
    suggestions: [
      'Consider international diversification',
      'Reduce overlapping mid-cap exposure',
      'Add small-cap allocation for higher growth potential',
    ],
  },
  {
    dimension: 'Cost Efficiency',
    score: 58,
    rationale: '4 of 6 funds are Regular plans. Annual expense drag of ₹12,600',
    suggestions: [
      'Switch HDFC and SBI funds to Direct plans',
      'Potential annual savings: ₹8,500+',
      'Consider index funds for large-cap allocation',
    ],
  },
  {
    dimension: 'Tax Efficiency',
    score: 65,
    rationale: 'ELSS provides 80C benefits. Some funds have short-term holdings.',
    suggestions: [
      'Hold equity funds for 1+ years to qualify for LTCG',
      'Utilize ₹1L LTCG exemption effectively',
      'Consider tax-loss harvesting opportunities',
    ],
  },
  {
    dimension: 'Risk Alignment',
    score: 78,
    rationale: 'Portfolio matches moderate risk profile. Good mix of large and mid caps.',
    suggestions: [
      'Maintain current equity/debt split',
      'Review allocation annually as you age',
      'Consider adding debt funds as you approach goals',
    ],
  },
  {
    dimension: 'Goal Readiness',
    score: 70,
    rationale: 'On track for retirement goal with current SIP. Gap in emergency fund.',
    suggestions: [
      'Build 6-month emergency fund in liquid funds',
      'Increase SIP by 10% annually',
      'Link specific funds to specific goals',
    ],
  },
  {
    dimension: 'Liquidity',
    score: 82,
    rationale: 'Most funds are liquid (except ELSS lock-in). Good redemption access.',
    suggestions: [
      'Maintain current liquidity levels',
      'Keep 3-6 months expenses in liquid/overnight funds',
      'Avoid over-allocation to ELSS beyond tax benefit',
    ],
  },
];

export const MOCK_TRANSACTIONS = [
  { date: '2022-01-15', fundName: 'HDFC Mid-Cap Opportunities Fund', type: 'purchase', amount: 10000, units: 35.714, nav: 280 },
  { date: '2022-02-15', fundName: 'HDFC Mid-Cap Opportunities Fund', type: 'purchase', amount: 10000, units: 33.333, nav: 300 },
  { date: '2022-03-15', fundName: 'HDFC Mid-Cap Opportunities Fund', type: 'purchase', amount: 10000, units: 31.25, nav: 320 },
  { date: '2022-01-15', fundName: 'SBI Bluechip Fund', type: 'purchase', amount: 10000, units: 25.0, nav: 400 },
  { date: '2022-02-15', fundName: 'SBI Bluechip Fund', type: 'purchase', amount: 10000, units: 24.39, nav: 410 },
  { date: '2022-03-15', fundName: 'SBI Bluechip Fund', type: 'purchase', amount: 10000, units: 23.81, nav: 420 },
];
